services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
        interval: 5s
        timeout: 5s
        retries: 5

  gmhelper-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      SMTP__Host: ${SMTP__Host}
      SMTP_Port: ${SMTP_Port}
      SMTP__Username: ${SMTP__Username}
      SMTP__Password: ${SMTP__Password}
      SMTP__From: ${SMTP__From}
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
      - "7057:7057"
    env_file:
      - .env
    volumes:
      - ./data-protection-keys:/root/.aspnet/DataProtection-Keys
    depends_on:
        postgres:
            condition: service_healthy

  gmhelper-client:
    build:
      context: ../gmhelper.ui
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ../gmhelper.ui:/app
      - /app/node_modules

  solution-hub:
    build:
      context: ../gmhelper.solution-hub
      dockerfile: Dockerfile
    container_name: solution-hub
    expose:
        - "50051"
    restart: unless-stopped

volumes:
  pgdata:
